version: '3.7'

services:
  jupyter:
    build: .
    command: jupyter notebook --ip 0.0.0.0 --port 4000 --allow-root
    
    volumes:
      - .:/home/user 
    ports:
      - 4000:4000 
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #       - driver: nvidia
    #         count: 1
    #         # device_ids: ['0', '3']
    #         capabilities: [gpu]